# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import basicmessage_pb2 as basicmessage__pb2


class BasicServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowMessage = channel.unary_unary(
        '/basicmessage.BasicService/ShowMessage',
        request_serializer=basicmessage__pb2.SimpleMessage.SerializeToString,
        response_deserializer=basicmessage__pb2.OutputMessage.FromString,
        )


class BasicServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BasicServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowMessage': grpc.unary_unary_rpc_method_handler(
          servicer.ShowMessage,
          request_deserializer=basicmessage__pb2.SimpleMessage.FromString,
          response_serializer=basicmessage__pb2.OutputMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'basicmessage.BasicService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
