# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentiment_analysis_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentiment_analysis_rpc.proto',
  package='sentiment_analysis_rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x1csentiment_analysis_rpc.proto\x12\x16sentiment_analysis_rpc\"\x1d\n\x0cInputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"o\n\x12TwitterCredentials\x12\x14\n\x0c\x63onsumer_key\x18\x01 \x01(\t\x12\x17\n\x0f\x63onsumer_secret\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x14\n\x0ctoken_secret\x18\x04 \x01(\t\"\xb4\x02\n\x13TwitterInputMessage\x12?\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32*.sentiment_analysis_rpc.TwitterCredentials\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x01(\t\x12\x11\n\tlanguages\x18\x04 \x01(\t\x12\r\n\x05query\x18\x05 \x01(\t\x12\x1c\n\x14messages_per_request\x18\x06 \x01(\x05\x12\x1a\n\x12max_requests_limit\x18\x07 \x01(\x05\x12\x11\n\tmsg_limit\x18\x08 \x01(\x05\x12\x12\n\ntime_limit\x18\t \x01(\x05\x12\x11\n\tfrom_date\x18\n \x01(\t\x12\x0f\n\x07to_date\x18\x0b \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x0c \x01(\t\"%\n\x14TwitterOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t2d\n\x0bShowMessage\x12U\n\x04show\x12$.sentiment_analysis_rpc.InputMessage\x1a%.sentiment_analysis_rpc.OutputMessage\"\x00\x32\x80\x01\n\x1aSentimentConsensusAnalysis\x12\x62\n\x11\x43onsensusAnalysis\x12$.sentiment_analysis_rpc.InputMessage\x1a%.sentiment_analysis_rpc.OutputMessage\"\x00\x32\x87\x01\n\x19TwitterHistoricalAnalysis\x12j\n\x12HistoricalAnalysis\x12+.sentiment_analysis_rpc.TwitterInputMessage\x1a%.sentiment_analysis_rpc.OutputMessage\"\x00\x32\x7f\n\x15TwitterStreamAnalysis\x12\x66\n\x0eStreamAnalysis\x12+.sentiment_analysis_rpc.TwitterInputMessage\x1a%.sentiment_analysis_rpc.OutputMessage\"\x00\x62\x06proto3')
)




_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='sentiment_analysis_rpc.InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sentiment_analysis_rpc.InputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='sentiment_analysis_rpc.OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sentiment_analysis_rpc.OutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=117,
)


_TWITTERCREDENTIALS = _descriptor.Descriptor(
  name='TwitterCredentials',
  full_name='sentiment_analysis_rpc.TwitterCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_key', full_name='sentiment_analysis_rpc.TwitterCredentials.consumer_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer_secret', full_name='sentiment_analysis_rpc.TwitterCredentials.consumer_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='sentiment_analysis_rpc.TwitterCredentials.access_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_secret', full_name='sentiment_analysis_rpc.TwitterCredentials.token_secret', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=230,
)


_TWITTERINPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterInputMessage',
  full_name='sentiment_analysis_rpc.TwitterInputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credentials', full_name='sentiment_analysis_rpc.TwitterInputMessage.credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='sentiment_analysis_rpc.TwitterInputMessage.product', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='environment', full_name='sentiment_analysis_rpc.TwitterInputMessage.environment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='languages', full_name='sentiment_analysis_rpc.TwitterInputMessage.languages', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='sentiment_analysis_rpc.TwitterInputMessage.query', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages_per_request', full_name='sentiment_analysis_rpc.TwitterInputMessage.messages_per_request', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_requests_limit', full_name='sentiment_analysis_rpc.TwitterInputMessage.max_requests_limit', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_limit', full_name='sentiment_analysis_rpc.TwitterInputMessage.msg_limit', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_limit', full_name='sentiment_analysis_rpc.TwitterInputMessage.time_limit', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_date', full_name='sentiment_analysis_rpc.TwitterInputMessage.from_date', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_date', full_name='sentiment_analysis_rpc.TwitterInputMessage.to_date', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_name', full_name='sentiment_analysis_rpc.TwitterInputMessage.db_name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=541,
)


_TWITTEROUTPUTMESSAGE = _descriptor.Descriptor(
  name='TwitterOutputMessage',
  full_name='sentiment_analysis_rpc.TwitterOutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sentiment_analysis_rpc.TwitterOutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=580,
)

_TWITTERINPUTMESSAGE.fields_by_name['credentials'].message_type = _TWITTERCREDENTIALS
DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE
DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterCredentials'] = _TWITTERCREDENTIALS
DESCRIPTOR.message_types_by_name['TwitterInputMessage'] = _TWITTERINPUTMESSAGE
DESCRIPTOR.message_types_by_name['TwitterOutputMessage'] = _TWITTEROUTPUTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:sentiment_analysis_rpc.InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:sentiment_analysis_rpc.OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)

TwitterCredentials = _reflection.GeneratedProtocolMessageType('TwitterCredentials', (_message.Message,), dict(
  DESCRIPTOR = _TWITTERCREDENTIALS,
  __module__ = 'sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:sentiment_analysis_rpc.TwitterCredentials)
  ))
_sym_db.RegisterMessage(TwitterCredentials)

TwitterInputMessage = _reflection.GeneratedProtocolMessageType('TwitterInputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTERINPUTMESSAGE,
  __module__ = 'sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:sentiment_analysis_rpc.TwitterInputMessage)
  ))
_sym_db.RegisterMessage(TwitterInputMessage)

TwitterOutputMessage = _reflection.GeneratedProtocolMessageType('TwitterOutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWITTEROUTPUTMESSAGE,
  __module__ = 'sentiment_analysis_rpc_pb2'
  # @@protoc_insertion_point(class_scope:sentiment_analysis_rpc.TwitterOutputMessage)
  ))
_sym_db.RegisterMessage(TwitterOutputMessage)



_SHOWMESSAGE = _descriptor.ServiceDescriptor(
  name='ShowMessage',
  full_name='sentiment_analysis_rpc.ShowMessage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=582,
  serialized_end=682,
  methods=[
  _descriptor.MethodDescriptor(
    name='show',
    full_name='sentiment_analysis_rpc.ShowMessage.show',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWMESSAGE)

DESCRIPTOR.services_by_name['ShowMessage'] = _SHOWMESSAGE


_SENTIMENTCONSENSUSANALYSIS = _descriptor.ServiceDescriptor(
  name='SentimentConsensusAnalysis',
  full_name='sentiment_analysis_rpc.SentimentConsensusAnalysis',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=685,
  serialized_end=813,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConsensusAnalysis',
    full_name='sentiment_analysis_rpc.SentimentConsensusAnalysis.ConsensusAnalysis',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTCONSENSUSANALYSIS)

DESCRIPTOR.services_by_name['SentimentConsensusAnalysis'] = _SENTIMENTCONSENSUSANALYSIS


_TWITTERHISTORICALANALYSIS = _descriptor.ServiceDescriptor(
  name='TwitterHistoricalAnalysis',
  full_name='sentiment_analysis_rpc.TwitterHistoricalAnalysis',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=816,
  serialized_end=951,
  methods=[
  _descriptor.MethodDescriptor(
    name='HistoricalAnalysis',
    full_name='sentiment_analysis_rpc.TwitterHistoricalAnalysis.HistoricalAnalysis',
    index=0,
    containing_service=None,
    input_type=_TWITTERINPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERHISTORICALANALYSIS)

DESCRIPTOR.services_by_name['TwitterHistoricalAnalysis'] = _TWITTERHISTORICALANALYSIS


_TWITTERSTREAMANALYSIS = _descriptor.ServiceDescriptor(
  name='TwitterStreamAnalysis',
  full_name='sentiment_analysis_rpc.TwitterStreamAnalysis',
  file=DESCRIPTOR,
  index=3,
  options=None,
  serialized_start=953,
  serialized_end=1080,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamAnalysis',
    full_name='sentiment_analysis_rpc.TwitterStreamAnalysis.StreamAnalysis',
    index=0,
    containing_service=None,
    input_type=_TWITTERINPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERSTREAMANALYSIS)

DESCRIPTOR.services_by_name['TwitterStreamAnalysis'] = _TWITTERSTREAMANALYSIS

# @@protoc_insertion_point(module_scope)
